# Generated by Django 4.0.5 on 2022-07-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_options_user_is_admin_user_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_deleted',
            new_name='deleted_at',
        ),
    ]
