# Generated by Django 4.0.5 on 2022-07-03 06:26

from django.db import migrations
import home.softDelete


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_is_deleted_user_deleted_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', home.softDelete.SoftDeleteManager()),
            ],
        ),
    ]
