# Generated by Django 4.0.5 on 2022-08-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_login_id_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=3905432, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
