# Generated by Django 4.0.5 on 2022-08-24 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.softDelete
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', home.softDelete.SoftDeleteManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', home.softDelete.SoftDeleteManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='lecturer_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_lecturer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='assignment_id',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='grader.assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='assignment_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grader.assignment'),
            preserve_default=False,
        ),
    ]
