# Generated by Django 4.0.5 on 2022-08-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0003_rename_course_id_assignment_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='course_code',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.IntegerField(default=9750, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.IntegerField(default=9660, max_length=10, primary_key=True, serialize=False),
        ),
    ]
