# Generated by Django 4.0.5 on 2022-08-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0004_rename_title_assignment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.IntegerField(default=3794, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.IntegerField(default=1800, max_length=10, primary_key=True, serialize=False),
        ),
    ]
