# Generated by Django 4.0.5 on 2022-08-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0006_alter_assignment_id_alter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.IntegerField(default=3168, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.IntegerField(default=6241, primary_key=True, serialize=False, unique=True),
        ),
    ]
