# Generated by Django 4.0.5 on 2022-08-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0011_rename_file_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='language',
            new_name='description',
        ),
    ]
