# Generated by Django 4.0.5 on 2022-09-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0012_rename_language_assignment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
