# Generated by Django 4.0.5 on 2022-09-24 11:51

from django.db import migrations, models
import django.db.models.deletion
import grader.models
import home.softDelete
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0014_alter_assignment_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to=grader.models.get_config_upload_to)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader.assignment')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', home.softDelete.SoftDeleteManager()),
            ],
        ),
    ]
