# Generated by Django 4.0.5 on 2022-09-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0017_remove_testcase_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
