# Generated by Django 4.0.5 on 2022-09-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0018_alter_submission_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='grade',
            new_name='score',
        ),
    ]
